### ISSUE TITLE
如何获取指定属性值

### ISSUE THREAD

**Issue by DerryName** [5i03/fvti_noCovSys_Automation#1]
如何抓包获取两个属性的值

**Comment by DerryName** [comment]
前端接口访问无法登录

**Comment by hiyuey3** [comment]
打开抓包软件后，打开小程序，并完成一次提交，然后回抓包软件查看对应数据

**Comment by 5i03** [comment]
@5i03 还有就是抓包软件要能支持解包SSL

**Comment by hiyuey3** [comment]
@5i03 还有就是抓包软件要能支持解包SSL

**Comment by DerryName** [comment]
有什么好用的抓包软件吗&nbsp;


南屿欣风
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月1日(星期四) 上午10:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [5i03/fvti_nCov_Auto_Reporter] 如何获取指定属性值 (Issue #1)





 
@5i03 还有就是抓包软件要能支持解包SSL

**Comment by hiyuey3** [comment]
@DerryName 我不知道你用的是什么操作系统，不同的软件适用不同的操作系统

**Comment by hiyuey3** [comment]
@DerryName 例如在苹果的电脑和手机中我使用proxyman

**Comment by DerryName** [comment]
我这边是Windows

&nbsp;


南屿欣风
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月1日(星期四) 上午10:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [5i03/fvti_nCov_Auto_Reporter] 如何获取指定属性值 (Issue #1)





 
@DerryName 我不知道你用的是什么操作系统，不同的软件适用不同的操作系统

**Comment by DerryName** [comment]
你方便添加联系方式吗？

&nbsp;


南屿欣风
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月1日(星期四) 上午10:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [5i03/fvti_nCov_Auto_Reporter] 如何获取指定属性值 (Issue #1)





 
@DerryName 例如在苹果的电脑和手机中我使用proxyman

**Comment by hiyuey3** [comment]
@DerryName Fiddler会是一个不错的选择

**Comment by DerryName** [comment]
但是他很难抓取到小程序的包

&nbsp;


南屿欣风
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月1日(星期四) 上午10:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [5i03/fvti_nCov_Auto_Reporter] 如何获取指定属性值 (Issue #1)





 
@DerryName Fiddler会是一个不错的选择

**Comment by DerryName** [comment]
你联系加我Q吧2668423389&nbsp;


南屿欣风
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月1日(星期四) 上午10:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [5i03/fvti_nCov_Auto_Reporter] 如何获取指定属性值 (Issue #1)





 
@DerryName Fiddler会是一个不错的选择

**Comment by hiyuey3** [comment]
行

**Comment by hiyuey3** [comment]
现在，不需要透过抓包取得这两个关键的值，执行脚本并输入账号密码将会自动获得

**Comment by DerryName** [comment]
但是执行脚本没有任何反应&nbsp;


南屿欣风
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月28日(星期三) 凌晨0:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [5i03/fvti_nCov_Auto_Reporter] 如何获取指定属性值 (Issue #1)





 
现在，不需要透过抓包取得这两个关键的值，执行脚本并输入账号密码将会自动获得

**Comment by hiyuey3** [comment]
如果脚本不按预期的工作,请执行下列检查单：
1.你的电脑正确安装了python 3.6.5 以上的版本（3.10 最佳），
2.成功执行了命令pip install -r requirement.txt
3.上述步骤后请在终端内执行 python main.py
If the script does not work as expected, please perform the following checklist.
1. your computer has python 3.6.5 or higher installed correctly (3.10 is best), and
2. the command "pip install -r requirement.txt" has been successfully executed
3. After the above steps, please execute "python main.py" in the terminal.

**Comment by 5i03** [comment]
你使用的是Windows操作系统吗？如果是，请稍等，我会提交新的comment来支持Windows，因为我是为我的服务器开发的，所以它并没有支持Windows

**Comment by hiyuey3** [comment]
> 但是执行脚本没有任何反应&nbsp;
> 
> 
> 
> 
> 
> 南屿欣风
> 
> ***@***.***
> 
> 
> 
> 
> 
> 
> 
> &nbsp;
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 
> 发件人: ***@***.***&gt;; 
> 
> 发送时间: 2022年9月28日(星期三) 凌晨0:00
> 
> 收件人: ***@***.***&gt;; 
> 
> 抄送: ***@***.***&gt;; ***@***.***&gt;; 
> 
> 主题: Re: [5i03/fvti_nCov_Auto_Reporter] 如何获取指定属性值 (Issue #1)
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
>  
> 
> 现在，不需要透过抓包取得这两个关键的值，执行脚本并输入账号密码将会自动获得
> 
>  
> 
> —
> 
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

你用Windows的cmd执行的吗？如果是，请尝试使用powershell 来执行脚本。使用cmd 可能会无法正常工作。

Did you execute it with Windows cmd? If so, try using powershell to execute the script. Using cmd may not work properly.

**Comment by hiyuey3** [comment]
更新的脚本并未向控制台打印任何文字，执行脚本没有报错就是执行成功，具体执行的情况请查看report.log。
The updated script does not print any text to the console, the execution of the script does not report an error is a successful execution, please check report.log for the specific implementation.

**Comment by DerryName** [comment]
用fiddler抓包是吗？&nbsp;


南屿欣风
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月1日(星期四) 上午10:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [5i03/fvti_nCov_Auto_Reporter] 如何获取指定属性值 (Issue #1)





 
打开抓包软件后，打开小程序，并完成一次提交，然后回抓包软件查看对应数据

**Comment by hiyuey3** [comment]
> 用fiddler抓包是吗？&nbsp; 南屿欣风 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年9月1日(星期四) 上午10:10 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [5i03/fvti_nCov_Auto_Reporter] 如何获取指定属性值 (Issue #1) 打开抓包软件后，打开小程序，并完成一次提交，然后回抓包软件查看对应数据 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

并不是，在检查到你的配置文件中没有令牌时，程序会要求你输入密码和账号，你只需执行，并在终端模拟器中输入你的账号和密码

**Comment by DerryName** [comment]
方便添加联系方式吗？&nbsp;


南屿欣风
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月1日(星期四) 上午10:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [5i03/fvti_nCov_Auto_Reporter] 如何获取指定属性值 (Issue #1)





 
@5i03 还有就是抓包软件要能支持解包SSL

**Comment by hiyuey3** [comment]
@DerryName 行，你的联络方式是？

**Comment by hiyuey3** [comment]
> 方便添加联系方式吗？&nbsp;
> 
> 
> 
> 
> 
> 南屿欣风
> 
> ***@***.***
> 
> 
> 
> 
> 
> 
> 
> &nbsp;
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 
> 发件人: ***@***.***&gt;; 
> 
> 发送时间: 2022年9月1日(星期四) 上午10:13
> 
> 收件人: ***@***.***&gt;; 
> 
> 抄送: ***@***.***&gt;; ***@***.***&gt;; 
> 
> 主题: Re: [5i03/fvti_nCov_Auto_Reporter] 如何获取指定属性值 (Issue #1)
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
>  
> 
> @5i03 还有就是抓包软件要能支持解包SSL
> 
>  
> 
> —
> 
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
不对啊，我记得我加过你
